export const agents = [
    {
        id: 1,
        name: "山田 明子",
        role: "キャリアアドバイザー",
        company: "パーソルキャリア (doda)",
        experience: 6,
        specialty: ["販売接客・サービス系", "IT・エンジニア系", "医療・介護・福祉系", "企画・クリエイティブ系", "事務・管理系"],
        bio: "エンジニア転職専門で8年の実績があります。スタートアップから大手まで幅広い企業とのネットワークを持っています。",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        tags: ["営業系", "事務・管理系"],
        // Detailed Profile Data
        selfIntro: "関西学院大学卒業後、新卒でアパレルの専門商社に入社し、欧州ブランドの代理店として多数のブランドを日本に紹介。\nその後、フルコミッションの営業の世界で自分の力を試したいと思い、外資系生命保険会社にてFPとして活動。\n営業未経験で人脈も無いところから、行動力を駆使して世界上位5%の成績であるMDRT基準を達成する。\nこの経験をもとに、キャリアの面から人生のビジョン達成を支援したいという思い、転職エージェントに転身。\n現在は「誰もが自分の強みを活かして活躍できる社会」を目指して、若手・中堅層のキャリアアップのために転職活動のサポートに従事。",
        achievements: "じっくりと相談者の希望を聞いて、最適な企業をご紹介します。",
        companyType: ["中小企業", "大企業"],
        area: ["東京都", "神奈川県"],
        interviewMethod: ["WEB面談", "対面面談"],
        hiringCategory: ["中途採用"]
    },
    {
        id: 2,
        name: "佐藤 健二",
        role: "エンジニア採用担当",
        company: "株式会社リクルート",
        experience: 10,
        specialty: ["IT・エンジニア系", "PM・Webディレクター"],
        bio: "元エンジニアの経験を活かし、技術的な視点から最適なキャリアプランをご提案します。",
        image: "https://images.unsplash.com/photo-1556157382-97eda2d62296?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        tags: ["IT・エンジニア系", "PM"],
        selfIntro: "SIerでの開発経験を経て、人材業界へ。技術的なバックグラウンドを活かし、エンジニアの皆様のキャリア形成をサポートします。",
        achievements: "年収アップ実績多数。技術スタックに合わせた企業提案が得意です。",
        companyType: ["ベンチャー", "メガベンチャー"],
        area: ["東京都", "リモート"],
        interviewMethod: ["WEB面談"],
        hiringCategory: ["中途採用", "ハイクラス"]
    },
    {
        id: 3,
        name: "鈴木 エミ",
        role: "クリエイティブエージェント",
        company: "マイナビクリエイター",
        experience: 4,
        specialty: ["Webデザイン", "UI/UXデザイン"],
        bio: "ポートフォリオの添削から面接対策まで、クリエイターの転職をトータルサポートします。",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        tags: ["Webデザイン", "UI/UX"],
        selfIntro: "デザイン制作会社でのディレクター経験があります。クリエイターの気持ちに寄り添ったサポートを心がけています。",
        achievements: "未経験からのクリエイター転職支援実績あり。",
        companyType: ["制作会社", "事業会社"],
        area: ["東京都", "大阪府"],
        interviewMethod: ["WEB面談", "対面面談"],
        hiringCategory: ["中途採用", "第二新卒"]
    },
    {
        id: 4,
        name: "田中 宏樹",
        role: "ハイクラス転職コンサルタント",
        company: "JAC Recruitment",
        experience: 15,
        specialty: ["管理職", "経営企画"],
        bio: "年収1000万円以上のハイクラス転職に特化。非公開求人を多数保有しています。",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        tags: ["管理職", "ハイクラス"],
        selfIntro: "外資系企業での人事経験を活かし、エグゼクティブ層のキャリア構築を支援します。",
        achievements: "CXOクラスの成約実績多数。",
        companyType: ["外資系", "日系大手"],
        area: ["全国", "海外"],
        interviewMethod: ["対面面談", "電話面談"],
        hiringCategory: ["ハイクラス", "エグゼクティブ"]
    },
    {
        id: 5,
        name: "山本 由紀",
        role: "AI/データサイエンス専門",
        company: "Type転職エージェント",
        experience: 3,
        specialty: ["AI・機械学習", "データサイエンティスト"],
        bio: "急成長中のAIベンチャーから大手SIerまで、最先端技術に関わる求人をご紹介します。",
        image: "https://images.unsplash.com/photo-1598550832236-81f27e3c7305?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        tags: ["AI", "データサイエンス"],
        selfIntro: "大学院でデータ分析を専攻。アカデミックな知見とビジネスの架け橋となる人材の支援を行っています。",
        achievements: "博士号取得者の民間企業就職支援実績あり。",
        companyType: ["AIベンチャー", "研究機関"],
        area: ["東京都"],
        interviewMethod: ["WEB面談"],
        hiringCategory: ["専門職", "研究職"]
    }
];
